<?xml version="1.0"?>
<section xml:id="unit-testing_testing-functions">
  <title>Testing Functions</title>
  <subsection><title>Introduction</title>
  <p>Melinda is writing a program that does some mathematical calculations. At the moment, she is working on adding some
            functionality to her program that requires rounding numbers to the nearest integer. She would normally use the built-in
            Python function <c>round</c> to do the job, but her program has a special requirement that numbers should be rounded up if
            the fractional portion is .6 or greater, instead of the usual .5 or greater. So, Melinda decides to write a function that
            rounds up numbers according to this requirement.</p>
  <p>She defines a function <c>round6</c> to do the job:</p>
  <pre>def round6(num):
    """returns num rounded to nearest int if fractional part is &gt;= .6"""

    return int(num + .6)</pre>
  <p>This function uses a valid approach to rounding, but is not quite correct (Melinda doesn't realize it yet &#x2014; can you
            spot the bug?).</p>
  <p>Now she needs to test the new code. There are two basic approaches Melinda could take to do her testing:</p>
  <p>
    <ol marker="1">
      <li>
        <p>Put the function into the program, modify the program to call the function at the appropriate point, then run the program.</p>
      </li>
      <li>
        <p>Test the function by itself, somehow.</p>
      </li>
    </ol>
  </p>
  <p>Which do you think will be more efficient?</p>
  <p>Melinda's program does complex mathematical calculations, and asks the user to enter 5 separate pieces of input before
            performing the calculations. If she goes with option 1, each time she runs the program to test the function,
            she must enter all 5 pieces of input. As you can imagine, that process is cumbersome and will not be very efficient.
            Also, if the program output is incorrect, it may be difficult to determine whether the fault is in the new function,
            or elsewhere in the program.</p>
  <p>Melinda decides to write a separate, short program to help her test her new function. The test program is very simple
            &#x2014; it contains only her new function and a bit of code to get some input, pass it to the function, and display the
            result. Here's what she writes:</p>
  <program xml:id="ac_round6_1" interactive="activecode" language="python">
    <input>
def round6(num):
    """returns num rounded to nearest int if fractional part is &gt;= .6"""

    return int(num + .6)

# ----- test program -------

x = float(input('Enter a number:'))
result = round6(x)
print('Result: ', result)
        </input>
  </program>
  <p>Before running the program, she jots down some test cases to help her in her testing:</p>
  <pre>              Input    Expected Output
              -------- ---------------
Test Case 1:       3.5               3
Test Case 2:       3.6               4
Test Case 3:       3.7               4</pre>
  <p>Try running the program with the input values above. Notice that the output isn't quite right.
            Can you figure out how to correct the bug?</p>
  <p>After analyzing her logic, Melinda corrects the bug by changing the return statement in the function as follows:</p>
  <pre>return int(num + .4)</pre>
  <p>She runs the test program again to verify that the function is working correctly. Then, she copies the
            <c>round6</c> function into her main program, confident that her rounding logic is correct.</p>
  <p>The program Melinda wrote to help her test her round6 function is an example of a unit test.</p>
  <note>
    <title>Unit Test</title>
    <p>A <term>unit test</term> is code that tests a function to determine if it works properly.</p>
  </note>
  <p>A unit test program like this one can dramatically reduce the effort it takes to test a new function, and can reduce the
            overall effort involved in adding functionality to a program. The savings tradeoff depends on the amount of effort
            required to write the test program, compared to the amount of effort required to test the function in the context of the
            main program for which the new function is being developed. Here, the function was relatively simple, and it probably
            wouldn't have taken Melinda too many iterations of testing the function in the context of the main program, with its
            five pieces of input. In this scenario, Melinda may not have saved much effort. However, if the function were more
            complex, writing a unit test would probably have helped reduce the overall effort. And, using some tricks I'll show you
            in the next sections, you can reduce the amount of effort required to write and run the unit test, making the case for
            writing unit tests even more compelling.</p>
        </subsection>
  <subsection xml:id="unit-testing_automated-unit-tests">
    <title>Automated Unit Tests</title>
    <p>The unit test program above is a manual unit test. A <term>manual unit test</term> gets input from the user, invokes the code
                under test, providing the input supplied by the user, and displays the result. (In our example, <c>round6</c> is the code
                under test.) Manual unit tests are helpful, but they can be improved in two ways:</p>
    <p>
      <ol marker="1">
        <li>
          <p>We can embed the test input directly within the unit test code, so the person running the test doesn't have to
                        come up with the test input or take the time to enter it.</p>
        </li>
        <li>
          <p>We can make the unit test report success or failure, instead of requiring the person running the test to
                        look at the output and determine whether the function worked correctly.</p>
        </li>
      </ol>
    </p>
    <p>We call a unit test that contains its own test input and produces a clear pass/fail indication an <term>automated
                    unit test</term>. Take a look at the following example:</p>
    <program xml:id="ac_round6_2" interactive="activecode" language="python">
      <input>
def round6(num):
    return int(num + .4)

# ---- automated unit test ----

result = round6(9.7)
if result == 10:
    print("Test 1: PASS")
else:
    print("Test 1: FAIL")

result = round6(8.5)
if result == 8:
    print("Test 2: PASS")
else:
    print("Test 2: FAIL")
        </input>
    </program>
    <p>This automated unit test invokes the <c>round6</c> function on predetermined test input, checks that the function produced the
                expected result, and displays a pass / fail message. Run it to see the test PASS messages.</p>
    <p>Try editing the round6 function above to introduce Melinda's original bug, then run it again to see the failure message.
                Notice the big advantage of an automated unit test: you can change the function being tested, run the unit test,
                and immediately see the test results for a whole series of tests. No hand-entry of test data, and no interpretation of the
                results. Clearly, once you have the test written, you can dramatically speed up your edit-test-debug cycle. The downside,
                of course, is that the unit test program itself takes more time to develop.</p>
  </subsection>
  <subsection xml:id="unit-testing_automated-unit-tests-with-assert">
    <title>Automated Unit Tests with <c>assert</c></title>
    <p>To help reduce the amount of effort required to develop an automated unit test, let's bring the <c>assert</c> statement into
                play. We can replace each <c>if</c> statement in the program above with an assert, as in the program below:</p>
    <program xml:id="ac_round6_3" interactive="activecode" language="python">
      <input>
def round6(num: float) -&gt; int:
    return int(num + .4)

# ---- automated unit test ----

result = round6(9.7)
assert result == 10

result = round6(8.5)
assert result == 8

print("All tests passed!")
        </input>
    </program>
    <p>Try running the program above to see the success message. Then, try altering the <c>round6</c> function to reintroduce the original
                bug, and see how the assertion failure pinpoints that the second test failed.</p>
    <p>We can streamline this program even further by eliminating the <c>result</c> variable:</p>
    <pre>assert round6(9.7) == 10
assert round6(8.5) == 8

print("All tests passed!")</pre>
    <p>This is Really Nice. We have a short test program that contains its own test input and displays an automated pass or
                fail indication.  Writing this program takes very little effort. We have the benefits of an automated test without
                having to write much code. Unit test programs are essentially <q>throw-away</q> programs that are used only during
                development, and it's important that they can be developed quickly and easily.</p>
  </subsection>
  <subsection xml:id="unit-testing_unit-tests-can-have-bugs">
    <title>Unit Tests can have bugs</title>
    <p>Unit tests, like the functions they test, can have bugs. So, when you run a unit test and it fails with an assert error,
                one of the first questions you need to ask yourself is: <q>Is the unit test correct?</q> If the unit test is incorrect, then
                you need to correct it, rather than spending time trying to find the bug in the function that the unit test is testing.</p>
    <p>For example, consider the following assert:</p>
    <pre>assert round6(9.2) == 10</pre>
    <p>This unit test is incorrect, because <c>round6</c> should produce the value 9, not 10, when given the parameter <c>9.2</c>.</p>
    <p>
      <term>Check your understanding</term>
    </p>
    <exercise label="mc_testfunc_1">
      <statement>
        <p>Rewrite the following 3 lines of code with a single assert:</p>
        <pre>result = engage_thruster(22)
if result != 'OK':
    print("Test 2: FAIL")</pre>
      </statement>
      <choices>
        <choice>
          <statement>
            <p>assert result != 'OK'</p>
          </statement>
          <feedback><p>
                    Incorrect. The assert should call the engage_thruster function. Try again.
                </p></feedback>
        </choice>
        <choice>
          <statement>
            <p>assert engage_thruster(22) == result</p>
          </statement>
          <feedback><p>
                    Incorrect. The assert should not assume the presence of a variable named result.
                </p></feedback>
        </choice>
        <choice>
          <statement>
            <p>assert engage_thruster(22) != 'OK'</p>
          </statement>
          <feedback><p>
                    Incorrect. This assert calls the engage_thruster function with the correct parameter, but interprets the result differently from the if statement provided.
                </p></feedback>
        </choice>
        <choice correct="yes">
          <statement>
            <p>assert engage_thruster(22) == 'OK'</p>
          </statement>
          <feedback><p>
                    Correct! This assert checks that the result of invoking engage_thruster(22) is the value 'OK'.
                </p></feedback>
        </choice>
      </choices>
    </exercise>
    <exercise label="mc_testfunc_2">
      <statement>
        <p>Consider the following function which is supposed to return the first character of its argument:</p>
        <pre>def get_first(msg):
    return msg[1]</pre>
        <p>Now, consider this unit test:</p>
        <pre>assert get_first('Bells') == 'B'</pre>
        <p>This assertion fails. Is the unit test in error, or the function it is testing?</p>
      </statement>
      <choices>
        <choice>
          <statement>
            <p>Unit test</p>
          </statement>
          <feedback><p>
                    Incorrect. The assertion correctly checks that get_first should return the first character in 'Bells', 'B'.
                </p></feedback>
        </choice>
        <choice correct="yes">
          <statement>
            <p>Tested function</p>
          </statement>
          <feedback><p>
                    Correct. The function code returns the second character of the parameter, not the first.
                </p></feedback>
        </choice>
        <choice>
          <statement>
            <p>Both are in error</p>
          </statement>
          <feedback><p>
                    Incorrect. The assertion correctly checks that get_first should return the first character in 'Bells', 'B'.
                </p></feedback>
        </choice>
        <choice>
          <statement>
            <p>Both are correct</p>
          </statement>
          <feedback><p>
                    Incorrect. The function code returns the second character of the parameter, not the first.
                </p></feedback>
        </choice>
      </choices>
    </exercise>
  </subsection>
</section>
